version: '3.8'

services:
  frontend:
    build: 
      context: ./restaurant-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - restaurant-network
    restart: unless-stopped  

  backend:
    build: 
      context: ./restaurant-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./restaurant-backend/.env
    networks:
      - restaurant-network
    restart: unless-stopped  

networks:
  restaurant-network:
    driver: bridge